version: '3.7'
services:
  # PostgreSQL
  postgres:
    container_name: postgres
    build: ./postgres
    env_file: ./.private/postgres.env
    ports:
      - '5432:5432'
    # command: printenv

  # Backend
  node_api:
    container_name: backend
    # image: node:11.6
    build: ./
    working_dir: /usr/src/oakleafcakes-crm-api
    env_file: ./.private/node.env
    ports:
      - '3000:3000'
    volumes:
      - ./:/usr/src/oakleafcakes-crm-api
    command: tail -F anything
